/* eslint-disable import/prefer-default-export */
import { StyleSheet } from 'react-native';
import { colors } from '../../../constants/styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  header: {
    position: 'absolute',
    top: 0,
    width: '100%',
    height: 85,
    flexDirection: 'row',
    backgroundColor: `${colors.headerOrange}`,
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  headerTitle: {
    fontSize: 21,
    fontStyle: 'italic',
    textAlign: 'center',
    color: `${colors.white}`,
    paddingBottom: 10,
  },
  addListButton: {
    width: 240,
    height: 50,
    borderRadius: 100,
    backgroundColor: `${colors.buttonOrange}`,
    shadowColor: `${colors.borderColor}`,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    elevation: 5, // Android
    shadowRadius: 20,
    shadowOpacity: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addListLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: `${colors.white}`,
  },
  emptyListHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0,
    color: `${colors.buttonLabel}`,
    paddingTop: 50,
  },
  emptyListText: {
    width: 209,
    fontSize: 16,
    paddingTop: 10,
    paddingBottom: 25,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    color: `${colors.emptyListText}`,
  },
  contentContainer: {
    borderRadius: 30,
    backgroundColor: `${colors.white}`,
    width: '95%',
    height: '100%',
    marginTop: -50,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  addProduct: {
    borderRadius: 26.5,
    backgroundColor: `${colors.white}`,
    borderStyle: 'dashed',
    borderWidth: 1,
    width: 277,
    height: 56,
    borderColor: `${colors.headerOrange}`,
    justifyContent: 'center',
  },
  addProductLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: 0.43,
    textAlign: 'center',
    color: `${colors.headerOrange}`,
  },
  itemsContainer: {
    height: '60%',
  },
  buttonContainer: {
    height: '40%',
    flexDirection: 'row',
  },
  communityContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignContent: 'center',
    alignItems: 'center'
  },
  input: {
    backgroundColor: 'white',
    width: 200,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: `${colors.borderColor}`,
    marginTop: 10,
  },
  listName: {
    fontSize: 30,
    fontWeight: '600',
    fontStyle: 'normal',
    lineHeight: 41,
    letterSpacing: 0.36,
    color: `${colors.white}`,
  },
  textContainer: {
    position: 'absolute',
    top: 150,
    left: 50,
    zIndex: 1,
    width: 300,
  },
  inlineTextContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonClose: {
    width: 200,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    backgroundColor: `${colors.orange}`,
    margin: 20,
  },
  textStyle: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  changeNameHeader: {
    fontSize: 20,
    paddingBottom: 20,
    color: `${colors.orange}`,
  },
  closeButton: {
    position: 'absolute',
    top: 5,
    right: 5,
  },
  comButton: {
    padding: 8,
    borderRadius: 8,
    marginRight: 5,
  },
  comContainer: {
    display: 'flex',
    flexDirection: 'row',
  }
});
