# Generated by Django 3.2.8 on 2021-12-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_0002_appuser_0004_usermeta_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
