# Generated by Django 3.2.8 on 2021-12-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211211_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.home'),
        ),
    ]
