# Generated by Django 3.2.8 on 2022-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211224_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
