# Generated by Django 3.2.8 on 2021-12-04 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_home_priceinstore_productbase_productincart_shoppingcart_store_usermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.AddField(
            model_name='productincart',
            name='adding_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.shoppingcart'),
        ),
    ]
