# Generated by Django 3.2.8 on 2021-12-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appuser'),
        ('base', '0004_usermeta_user'),
    ]

    operations = [
    ]
