# Generated by Django 3.2.8 on 2021-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_0002_appuser_0004_usermeta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='photo',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
