# Generated by Django 3.2.8 on 2021-12-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211222_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='base.productbase'),
        ),
    ]
