# Generated by Django 3.2.8 on 2022-03-03 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_productbase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
