# Generated by Django 3.2.8 on 2022-03-12 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20220303_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Community',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='home_owner',
            new_name='community_owner',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='home',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.community'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermeta',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, to='base.Community'),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='shopping_carts',
            field=models.ManyToManyField(to='base.ShoppingCart'),
        ),
    ]
