# Generated by Django 3.2.8 on 2022-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220312_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='base.ProductInCart'),
        ),
    ]
