# Generated by Django 3.2.8 on 2022-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='community',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='community',
            field=models.ManyToManyField(blank=True, null=True, to='base.Community'),
        ),
    ]
