# Generated by Django 3.2.8 on 2022-03-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220312_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='community',
            new_name='communities',
        ),
    ]
