# Generated by Django 3.2.8 on 2022-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220410_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='communities',
            field=models.ManyToManyField(to='base.Community'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(to='base.ProductInCart'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='communities',
            field=models.ManyToManyField(to='base.Community'),
        ),
    ]
