# Generated by Django 3.2.8 on 2022-04-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0023_productbase_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
