# Generated by Django 3.2.8 on 2022-04-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_community_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_code',
        ),
    ]
