# Generated by Django 3.2.8 on 2022-04-14 15:07

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_community_community_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
