# Generated by Django 3.2.8 on 2022-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_community_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
