# Generated by Django 3.2.8 on 2022-05-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0028_usermeta_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='communities',
            field=models.ManyToManyField(blank=True, to='base.Community'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(blank=True, to='base.ProductInCart'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_products',
            field=models.ManyToManyField(blank=True, to='base.ProductBase'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='communities',
            field=models.ManyToManyField(blank=True, to='base.Community'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='shopping_carts',
            field=models.ManyToManyField(blank=True, to='base.ShoppingCart'),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_bought', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.productbase')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.shoppingcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
