# Generated by Django 3.2.8 on 2022-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220501_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
