# Generated by Django 3.2.8 on 2022-05-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_productbase_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbase',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
