# Generated by Django 3.2.8 on 2022-05-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20220505_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
