# Generated by Django 3.2.8 on 2022-05-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20220505_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='avatar',
        ),
    ]
