# Generated by Django 3.2.8 on 2022-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_usermeta_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
