# Generated by Django 3.2.8 on 2022-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_usermeta_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbase',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
